- hosts: localhost
  vars_files: 
    - var.yml
  tasks: 

  - name: Sending an e-mail using Gmail SMTP servers
    mail:
     host: smtp.gmail.com
     port: 587
     username: "{{ uname }}"
     password: "{{ mypass }}"
     to: asifsayyad143@gmail.com
     subject: Ansible-report
     body:  System has been successfully provisioned.
 

